# Generated by Django 2.2 on 2019-04-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('personal_nid', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pet_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, unique=True)),
                ('pet_name_1', models.CharField(blank=True, max_length=100, unique=True)),
                ('pet_name_2', models.CharField(blank=True, max_length=100, unique=True)),
                ('pet_name_3', models.CharField(blank=True, max_length=100, unique=True)),
                ('pet_name_4', models.CharField(blank=True, max_length=100, unique=True)),
                ('pet_name_5', models.CharField(blank=True, max_length=100, unique=True)),
                ('pet_name_6', models.CharField(blank=True, max_length=100, unique=True)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_choice.personal_info')),
                ('pet_color', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='personal_choice.color')),
            ],
        ),
    ]
