# Generated by Django 2.2 on 2019-04-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_choice', '0002_auto_20190427_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='owner_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_choice.personal_info'),
        ),
    ]
