# Generated by Django 2.2 on 2019-04-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_choice', '0003_auto_20190427_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='pet_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal_choice.color'),
        ),
    ]
