# Generated by Django 2.2 on 2019-04-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_choice', '0004_auto_20190427_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('nid', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pet_id',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='owner_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_choice.customer_info'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_choice.color'),
        ),
        migrations.DeleteModel(
            name='personal_info',
        ),
        migrations.AddField(
            model_name='pet_info',
            name='pet_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal_choice.pet_id'),
            preserve_default=False,
        ),
    ]
