# Generated by Django 2.2 on 2019-04-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_choice', '0005_auto_20190427_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_id',
        ),
        migrations.DeleteModel(
            name='pet_id',
        ),
    ]
