# Generated by Django 2.2 on 2019-04-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_choice', '0006_auto_20190427_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_name_1',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_name_2',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_name_3',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_name_4',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_name_5',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_name_6',
        ),
    ]
